In [1]:
import pandas as pd
from sqlalchemy import create_engine
output_data_file = "rottentomatoes_2020.csv"

In [2]:
# Store the Wikipedia URL
movies_2020 = "https://www.rottentomatoes.com/top/bestofrt/?year=2020"

# Use Pandas to scrape Wikipedia page for tables
movies = pd.read_html(movies_2020)

In [3]:
# Grab the first table
movies = movies[2]
movies

,Rank,RatingTomatometer,Title,No. of Reviews
0,1.0,98%,Portrait of a Lady on Fire (Portrait de la jeu...,303
1,2.0,89%,1917 (2020),448
2,3.0,91%,The Invisible Man (2020),392
3,4.0,99%,Never Rarely Sometimes Always (2020),205
4,5.0,98%,Hamilton (2020),183
...,...,...,...,...
95,96.0,88%,Les Misérables (2020),187
96,97.0,94%,Calm with Horses (The Shadow of Violence) (2020),65
97,98.0,93%,And Then We Danced (2020),83
98,99.0,95%,My Darling Vivian (2020),44
99,100.0,95%,Dinner in America (2020),44

In [8]:
df = movies.rename(columns={'Rank': 'rank', 'No. of Reviews': 'num_reviews', 'Title': 'title_2020', 'RatingTomatometer': 'rating'})

In [9]:
df

,rank,rating,title_2020,num_reviews
0,1.0,98%,Portrait of a Lady on Fire (Portrait de la jeu...,303
1,2.0,89%,1917 (2020),448
2,3.0,91%,The Invisible Man (2020),392
3,4.0,99%,Never Rarely Sometimes Always (2020),205
4,5.0,98%,Hamilton (2020),183
...,...,...,...,...
95,96.0,88%,Les Misérables (2020),187
96,97.0,94%,Calm with Horses (The Shadow of Violence) (2020),65
97,98.0,93%,And Then We Danced (2020),83
98,99.0,95%,My Darling Vivian (2020),44
99,100.0,95%,Dinner in America (2020),44

In [7]:
#movies.to_csv(output_data_file, index=False)